title: Yon Kim
description: Yon Kim's study blog
theme: just-the-docs

#url: https://just-the-docs.github.io
url: https://yyonkim.github.io

aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
  #Template Repository: https://github.com/yyonkim/yyonkim.github.io
  Tags: https://yyonkim.github.io/docs/Tags/Tags.html
plugins:
    - jekyll-seo-tag
compress_html:
  blanklines: true
# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Build settings

header_pages:
  - tag/index.md
